### ISSUE TITLE
Design DRC CI job

### ISSUE THREAD

**Issue by jaylamb** [apcountryman/prototype-kicad-project-ci-cd#8]
**Add design rules compliance CI job**

Use the [KiAuto](https://github.com/INTI-CMNB/KiAuto) submodule's [pcbnew_do](https://github.com/apcountryman/KiAuto/blob/9cca08928ec912862559d5dbab0540f1d0747974/src/pcbnew_do) script (run_drc) to ensure project printed circuit board layout(s) comply with project design rules.

- [ ] Add design rules compliance check CI script (`ci/check-electrical-rules-compliance`)
    - [ ] Supported options:
        - [ ] `--help`: See other project scripts
        - [ ] `--version`: See other project scripts
    - [ ] `function error()`: See other project scripts
    - [ ] `function abort()`: See other project scripts
    - [ ] `function display_help_text()`: See other project scripts
    - [ ] `function display_version()`: See other project scripts
    - [ ] `function main()`: See other project scripts
    - [ ] `function check_design_rules_compliance()`:

    ```bash
    local layouts; mapfile -t layouts < <( git -C "$repository" ls-files 
    '*.kicad_pcb' ':!:*-sheet-*.sch' | xargs -r -d '\n' -I '{}' find "$repository/{}" ); 
    readonly layouts

    for layout in "${layouts[@]}"; do
        if ! "$repository/utilities/KiAuto/src/pcbnew_do" run_drc -w 
    "$layout" "$repository"; then
            cat "$repository/"*.drc
            abort
        fi
    done
    ```
- [ ] Add design rules compliance check CI job (`check-design-rules-compliance`) to `.github/workflows/ci.yml`
    - [ ] `name: Check design rules compliance`
    - [ ] Steps:
        - [ ] Checkout (needs submodules)
        - [ ] `name: Check design rules compliance`, `run: ./ci/check-design-rules-compliance`

**Comment by apcountryman** [comment]
A few things:
- The `git ls-files` invocation doesn't need the negative matcher for schematic sheet files.
- According to the KiAuto documentation, DRC reports use a `.drt` file extension, not `.drc`.
- It would be useful to have an option to ignore unconnected net errors during the initial layout of a board so that it doesn't have to all be done at once. KiAuto's `--ignore_unconnected` option should make this simple to implement.

Other than these, this design LGTM. I'll open a `type-feature` issue for implementing this new feature shortly.
